name: Bug Report
description: Report a bug in agentsync
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `agentsync sync`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages if any.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Config
      description: Your `agentsync.yaml` (remove sensitive data).
      render: yaml

  - type: input
    id: version
    attributes:
      label: agentsync version
      description: Output of `agentsync --version`.
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "macOS 15, Ubuntu 24.04, Windows 11"
    validations:
      required: true
